Update to latest PromiseKit
inloop/CodableStore pull request #15
Opened 2018-11-06 18:55 UTC by jakubknejzlik

Hello guys @jakubpetrik @VilemKurz 👋

There's bunch of code changes, but the tests finally passed! Thank you for your review in advance. Change requests expected :)

tldr:
- PromiseKit is completely refactored out as extension
- methods now return `CodableStoreRequest` which is going to be used for cancellation 
- any idead how to write `CodableStoreRequest.send` method nicer are welcome 🙏

2018-11-21 12:58 UTC, VilemKurz commented on CodableStore/Classes/Environment.swift
> +
space

2018-12-12 08:47 UTC, tomassliz requested changes
I've discovered two issues in this update:

1. UI API is called on a background thread: `UIApplication.setNetworkActivityIndicatorVisible`
2. Deserialization of objects doesn't set correctly `dateDecodingStrategy` & `keyDecodingStrategy`. That's because casting on line 58 & 59 in `Serialization.swift` always fails:
```swift
public func deserialize<T: Decodable>() throws -> T {
    if let data = self as? T {
        return data
    } else {
        let decoder = JSONDecoder()

        // THIS TYPE CASTING ALWAYS FAILS
        decoder.dateDecodingStrategy = (T.self as? CustomDateDecodable.Type)?.dateDecodingStrategy ?? .iso8601
        decoder.keyDecodingStrategy = (T.self as? CustomKeyDecodable.Type)?.keyDecodingStrategy ?? .useDefaultKeys

        return try decoder.decode(T.self, from: self)
    }
}
```
But tests don't catch this issue so the should be updated too.

2019-01-25 07:35 UTC, jakubpetrik commented
@tomassliz I've added a test to see if custom strategy is used or not and it indeed is. Can you please give some minimal example in which it is failing for you? Also network indicator should be now fixed.

2019-01-25 15:48 UTC, jakubpetrik submitted a review, later dismissed

2019-01-25 16:23 UTC, 3ducation1 commented
@jakubpetrik I will try to post some example during this weekend.

2019-01-25 16:24 UTC, tomassliz commented
@jakubpetrik I will try to post some example during this weekend.

2019-01-26 12:20 UTC, tomassliz commented
@jakubpetrik I'm a little bit stuck. I can't replicate errors in tests but I have project which is failing. I can send you the project source with more info on email. Are you ok with that?

2019-01-28 10:10 UTC, radimhalfar approved these changes

2019-01-28 10:11 UTC, jakubpetrik commented
> @jakubpetrik I'm a little bit stuck. I can't replicate errors in tests but I have project which is failing. I can send you the project source with more info on email. Are you ok with that?

sure. :)

2019-01-28 15:43 UTC, tomassliz commented
> @tomassliz sure. :)

@jakubpetrik OK, can you send me your e-mail please? Just write me on iCloud.com email joined with my GitHub username.

2019-01-30 20:51 UTC, jakubpetrik commented
Ok. I can now confirm that issue with getting custom strategies still exists. 
Issue is when `T` is `Optional<CustomDateDecodable>`. I will try to fix that.

2019-02-04 16:16 UTC, tomassliz approved these changes

2019-02-04 16:21 UTC, tomassliz commented
@jakubpetrik @jakubknejzlik I verified changes and it's ok now 👍  Shall we merge this PR?

2019-02-12 00:51 UTC, jakubpetrik approved these changes

2019-02-12 00:52 UTC, jakubpetrik commented
Let's merge it please. @jakubknejzlik

2019-02-12 14:56 UTC, merged